// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.2
// source: permission_model.proto

// import "google/protobuf/struct.proto";

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePermissionGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId        int32  `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	AppPackageId string `protobuf:"bytes,2,opt,name=appPackageId,proto3" json:"appPackageId,omitempty"`
}

func (x *CreatePermissionGroupRequest) Reset() {
	*x = CreatePermissionGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePermissionGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionGroupRequest) ProtoMessage() {}

func (x *CreatePermissionGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionGroupRequest.ProtoReflect.Descriptor instead.
func (*CreatePermissionGroupRequest) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePermissionGroupRequest) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *CreatePermissionGroupRequest) GetAppPackageId() string {
	if x != nil {
		return x.AppPackageId
	}
	return ""
}

type CreatePermissionGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreatePermissionGroupResponse) Reset() {
	*x = CreatePermissionGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePermissionGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionGroupResponse) ProtoMessage() {}

func (x *CreatePermissionGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionGroupResponse.ProtoReflect.Descriptor instead.
func (*CreatePermissionGroupResponse) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{1}
}

type UpdatePermissionGroupInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId        int64 `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	AppPackageId int64 `protobuf:"varint,2,opt,name=appPackageId,proto3" json:"appPackageId,omitempty"`
	GroupId      int64 `protobuf:"varint,3,opt,name=groupId,proto3" json:"groupId,omitempty"`
}

func (x *UpdatePermissionGroupInfoRequest) Reset() {
	*x = UpdatePermissionGroupInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePermissionGroupInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionGroupInfoRequest) ProtoMessage() {}

func (x *UpdatePermissionGroupInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionGroupInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdatePermissionGroupInfoRequest) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePermissionGroupInfoRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *UpdatePermissionGroupInfoRequest) GetAppPackageId() int64 {
	if x != nil {
		return x.AppPackageId
	}
	return 0
}

func (x *UpdatePermissionGroupInfoRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type UpdatePermissionGroupInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePermissionGroupInfoResponse) Reset() {
	*x = UpdatePermissionGroupInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePermissionGroupInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionGroupInfoResponse) ProtoMessage() {}

func (x *UpdatePermissionGroupInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionGroupInfoResponse.ProtoReflect.Descriptor instead.
func (*UpdatePermissionGroupInfoResponse) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{3}
}

type CollaboratorColumnUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId     int64  `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	OrgId     int64  `protobuf:"varint,2,opt,name=orgId,proto3" json:"orgId,omitempty"`
	TableId   int64  `protobuf:"varint,3,opt,name=tableId,proto3" json:"tableId,omitempty"`
	FieldName string `protobuf:"bytes,4,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
	UserId    int64  `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`
	DeptId    int64  `protobuf:"varint,6,opt,name=deptId,proto3" json:"deptId,omitempty"`
}

func (x *CollaboratorColumnUser) Reset() {
	*x = CollaboratorColumnUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollaboratorColumnUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollaboratorColumnUser) ProtoMessage() {}

func (x *CollaboratorColumnUser) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollaboratorColumnUser.ProtoReflect.Descriptor instead.
func (*CollaboratorColumnUser) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{4}
}

func (x *CollaboratorColumnUser) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *CollaboratorColumnUser) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *CollaboratorColumnUser) GetTableId() int64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *CollaboratorColumnUser) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *CollaboratorColumnUser) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CollaboratorColumnUser) GetDeptId() int64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

type CollaboratorUsersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*CollaboratorColumnUser `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *CollaboratorUsersRequest) Reset() {
	*x = CollaboratorUsersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollaboratorUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollaboratorUsersRequest) ProtoMessage() {}

func (x *CollaboratorUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollaboratorUsersRequest.ProtoReflect.Descriptor instead.
func (*CollaboratorUsersRequest) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{5}
}

func (x *CollaboratorUsersRequest) GetUsers() []*CollaboratorColumnUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type CollaboratorUsersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//repeated int64 ids = 1;  // collaboratorId
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *CollaboratorUsersResponse) Reset() {
	*x = CollaboratorUsersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollaboratorUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollaboratorUsersResponse) ProtoMessage() {}

func (x *CollaboratorUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollaboratorUsersResponse.ProtoReflect.Descriptor instead.
func (*CollaboratorUsersResponse) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{6}
}

func (x *CollaboratorUsersResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type CollaboratorUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId     int64  `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	TableId   int64  `protobuf:"varint,2,opt,name=tableId,proto3" json:"tableId,omitempty"` // 指任务,缺陷等编号
	FieldName string `protobuf:"bytes,3,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
	OrgId     int64  `protobuf:"varint,4,opt,name=orgId,proto3" json:"orgId,omitempty"`
	UserId    int64  `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`
	DeptId    int64  `protobuf:"varint,6,opt,name=deptId,proto3" json:"deptId,omitempty"`
}

func (x *CollaboratorUserRequest) Reset() {
	*x = CollaboratorUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollaboratorUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollaboratorUserRequest) ProtoMessage() {}

func (x *CollaboratorUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollaboratorUserRequest.ProtoReflect.Descriptor instead.
func (*CollaboratorUserRequest) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{7}
}

func (x *CollaboratorUserRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *CollaboratorUserRequest) GetTableId() int64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *CollaboratorUserRequest) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *CollaboratorUserRequest) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *CollaboratorUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CollaboratorUserRequest) GetDeptId() int64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

type CollaboratorUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CollaboratorUserResponse) Reset() {
	*x = CollaboratorUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollaboratorUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollaboratorUserResponse) ProtoMessage() {}

func (x *CollaboratorUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollaboratorUserResponse.ProtoReflect.Descriptor instead.
func (*CollaboratorUserResponse) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{8}
}

func (x *CollaboratorUserResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserCollaboratorRoleIdsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId   int64   `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	OrgId   int64   `protobuf:"varint,2,opt,name=orgId,proto3" json:"orgId,omitempty"`
	UserId  int64   `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	TableId int64   `protobuf:"varint,4,opt,name=tableId,proto3" json:"tableId,omitempty"`
	DeptIds []int64 `protobuf:"varint,5,rep,packed,name=deptIds,proto3" json:"deptIds,omitempty"`
}

func (x *GetUserCollaboratorRoleIdsRequest) Reset() {
	*x = GetUserCollaboratorRoleIdsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserCollaboratorRoleIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCollaboratorRoleIdsRequest) ProtoMessage() {}

func (x *GetUserCollaboratorRoleIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCollaboratorRoleIdsRequest.ProtoReflect.Descriptor instead.
func (*GetUserCollaboratorRoleIdsRequest) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserCollaboratorRoleIdsRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *GetUserCollaboratorRoleIdsRequest) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *GetUserCollaboratorRoleIdsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserCollaboratorRoleIdsRequest) GetTableId() int64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *GetUserCollaboratorRoleIdsRequest) GetDeptIds() []int64 {
	if x != nil {
		return x.DeptIds
	}
	return nil
}

type GetUserCollaboratorRoleIdsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleIds []int64 `protobuf:"varint,1,rep,packed,name=roleIds,proto3" json:"roleIds,omitempty"`
}

func (x *GetUserCollaboratorRoleIdsResponse) Reset() {
	*x = GetUserCollaboratorRoleIdsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserCollaboratorRoleIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCollaboratorRoleIdsResponse) ProtoMessage() {}

func (x *GetUserCollaboratorRoleIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCollaboratorRoleIdsResponse.ProtoReflect.Descriptor instead.
func (*GetUserCollaboratorRoleIdsResponse) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserCollaboratorRoleIdsResponse) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type MemberFieldRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId     int64  `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	OrgId     int64  `protobuf:"varint,2,opt,name=orgId,proto3" json:"orgId,omitempty"`
	TableId   int64  `protobuf:"varint,3,opt,name=tableId,proto3" json:"tableId,omitempty"`
	FieldName string `protobuf:"bytes,4,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
}

func (x *MemberFieldRequest) Reset() {
	*x = MemberFieldRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberFieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberFieldRequest) ProtoMessage() {}

func (x *MemberFieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberFieldRequest.ProtoReflect.Descriptor instead.
func (*MemberFieldRequest) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{11}
}

func (x *MemberFieldRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *MemberFieldRequest) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *MemberFieldRequest) GetTableId() int64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *MemberFieldRequest) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

type MemberFieldResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *MemberFieldResponse) Reset() {
	*x = MemberFieldResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberFieldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberFieldResponse) ProtoMessage() {}

func (x *MemberFieldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberFieldResponse.ProtoReflect.Descriptor instead.
func (*MemberFieldResponse) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{12}
}

func (x *MemberFieldResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type BatchMigrateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgIds []int64 `protobuf:"varint,1,rep,packed,name=orgIds,proto3" json:"orgIds,omitempty"`
}

func (x *BatchMigrateRequest) Reset() {
	*x = BatchMigrateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchMigrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMigrateRequest) ProtoMessage() {}

func (x *BatchMigrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMigrateRequest.ProtoReflect.Descriptor instead.
func (*BatchMigrateRequest) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{13}
}

func (x *BatchMigrateRequest) GetOrgIds() []int64 {
	if x != nil {
		return x.OrgIds
	}
	return nil
}

type BatchMigrateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *BatchMigrateResponse) Reset() {
	*x = BatchMigrateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchMigrateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMigrateResponse) ProtoMessage() {}

func (x *BatchMigrateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMigrateResponse.ProtoReflect.Descriptor instead.
func (*BatchMigrateResponse) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{14}
}

func (x *BatchMigrateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetCollaboratorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId   int64 `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	OrgId   int64 `protobuf:"varint,2,opt,name=orgId,proto3" json:"orgId,omitempty"`
	TableId int64 `protobuf:"varint,3,opt,name=tableId,proto3" json:"tableId,omitempty"`
	// string fieldName       = 4;
	AllUser bool `protobuf:"varint,4,opt,name=allUser,proto3" json:"allUser,omitempty"`
}

func (x *GetCollaboratorsRequest) Reset() {
	*x = GetCollaboratorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCollaboratorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollaboratorsRequest) ProtoMessage() {}

func (x *GetCollaboratorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollaboratorsRequest.ProtoReflect.Descriptor instead.
func (*GetCollaboratorsRequest) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{15}
}

func (x *GetCollaboratorsRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *GetCollaboratorsRequest) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *GetCollaboratorsRequest) GetTableId() int64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *GetCollaboratorsRequest) GetAllUser() bool {
	if x != nil {
		return x.AllUser
	}
	return false
}

type AppPerGroupListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HasDelete bool   `protobuf:"varint,2,opt,name=hasDelete,proto3" json:"hasDelete,omitempty"`
	HasEdit   bool   `protobuf:"varint,3,opt,name=hasEdit,proto3" json:"hasEdit,omitempty"`
	LangCode  string `protobuf:"bytes,4,opt,name=langCode,proto3" json:"langCode,omitempty"`
	Name      string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	ReadOnly  int32  `protobuf:"varint,6,opt,name=readOnly,proto3" json:"readOnly,omitempty"`
	Remake    string `protobuf:"bytes,7,opt,name=remake,proto3" json:"remake,omitempty"`
}

func (x *AppPerGroupListItem) Reset() {
	*x = AppPerGroupListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppPerGroupListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppPerGroupListItem) ProtoMessage() {}

func (x *AppPerGroupListItem) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppPerGroupListItem.ProtoReflect.Descriptor instead.
func (*AppPerGroupListItem) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{16}
}

func (x *AppPerGroupListItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppPerGroupListItem) GetHasDelete() bool {
	if x != nil {
		return x.HasDelete
	}
	return false
}

func (x *AppPerGroupListItem) GetHasEdit() bool {
	if x != nil {
		return x.HasEdit
	}
	return false
}

func (x *AppPerGroupListItem) GetLangCode() string {
	if x != nil {
		return x.LangCode
	}
	return ""
}

func (x *AppPerGroupListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppPerGroupListItem) GetReadOnly() int32 {
	if x != nil {
		return x.ReadOnly
	}
	return 0
}

func (x *AppPerGroupListItem) GetRemake() string {
	if x != nil {
		return x.Remake
	}
	return ""
}

type Collaborator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar     string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Type       string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Status     int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	IsDelete   int32                  `protobuf:"varint,6,opt,name=isDelete,proto3" json:"isDelete,omitempty"`
	PerGroups  []*AppPerGroupListItem `protobuf:"bytes,7,rep,name=perGroups,proto3" json:"perGroups,omitempty"`
	IsSysAdmin bool                   `protobuf:"varint,8,opt,name=isSysAdmin,proto3" json:"isSysAdmin,omitempty"`
	IsSubAdmin bool                   `protobuf:"varint,9,opt,name=isSubAdmin,proto3" json:"isSubAdmin,omitempty"`
	IsOwner    bool                   `protobuf:"varint,10,opt,name=isOwner,proto3" json:"isOwner,omitempty"`
}

func (x *Collaborator) Reset() {
	*x = Collaborator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Collaborator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collaborator) ProtoMessage() {}

func (x *Collaborator) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collaborator.ProtoReflect.Descriptor instead.
func (*Collaborator) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{17}
}

func (x *Collaborator) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Collaborator) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Collaborator) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Collaborator) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Collaborator) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Collaborator) GetIsDelete() int32 {
	if x != nil {
		return x.IsDelete
	}
	return 0
}

func (x *Collaborator) GetPerGroups() []*AppPerGroupListItem {
	if x != nil {
		return x.PerGroups
	}
	return nil
}

func (x *Collaborator) GetIsSysAdmin() bool {
	if x != nil {
		return x.IsSysAdmin
	}
	return false
}

func (x *Collaborator) GetIsSubAdmin() bool {
	if x != nil {
		return x.IsSubAdmin
	}
	return false
}

func (x *Collaborator) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

type GetCollaboratorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Collaborators []*Collaborator `protobuf:"bytes,1,rep,name=collaborators,proto3" json:"collaborators,omitempty"`
}

func (x *GetCollaboratorsResponse) Reset() {
	*x = GetCollaboratorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCollaboratorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollaboratorsResponse) ProtoMessage() {}

func (x *GetCollaboratorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollaboratorsResponse.ProtoReflect.Descriptor instead.
func (*GetCollaboratorsResponse) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{18}
}

func (x *GetCollaboratorsResponse) GetCollaborators() []*Collaborator {
	if x != nil {
		return x.Collaborators
	}
	return nil
}

type GetCollaboratorUserIdsAndDeptIdsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId     int64  `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	OrgId     int64  `protobuf:"varint,2,opt,name=orgId,proto3" json:"orgId,omitempty"`
	TableId   int64  `protobuf:"varint,3,opt,name=tableId,proto3" json:"tableId,omitempty"`
	FieldName string `protobuf:"bytes,4,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
}

func (x *GetCollaboratorUserIdsAndDeptIdsRequest) Reset() {
	*x = GetCollaboratorUserIdsAndDeptIdsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCollaboratorUserIdsAndDeptIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollaboratorUserIdsAndDeptIdsRequest) ProtoMessage() {}

func (x *GetCollaboratorUserIdsAndDeptIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollaboratorUserIdsAndDeptIdsRequest.ProtoReflect.Descriptor instead.
func (*GetCollaboratorUserIdsAndDeptIdsRequest) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{19}
}

func (x *GetCollaboratorUserIdsAndDeptIdsRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *GetCollaboratorUserIdsAndDeptIdsRequest) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *GetCollaboratorUserIdsAndDeptIdsRequest) GetTableId() int64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *GetCollaboratorUserIdsAndDeptIdsRequest) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

type GetCollaboratorUserIdsAndDeptIdsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIds []int64 `protobuf:"varint,1,rep,packed,name=userIds,proto3" json:"userIds,omitempty"`
	DeptIds []int64 `protobuf:"varint,2,rep,packed,name=deptIds,proto3" json:"deptIds,omitempty"`
}

func (x *GetCollaboratorUserIdsAndDeptIdsResponse) Reset() {
	*x = GetCollaboratorUserIdsAndDeptIdsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCollaboratorUserIdsAndDeptIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollaboratorUserIdsAndDeptIdsResponse) ProtoMessage() {}

func (x *GetCollaboratorUserIdsAndDeptIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollaboratorUserIdsAndDeptIdsResponse.ProtoReflect.Descriptor instead.
func (*GetCollaboratorUserIdsAndDeptIdsResponse) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{20}
}

func (x *GetCollaboratorUserIdsAndDeptIdsResponse) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *GetCollaboratorUserIdsAndDeptIdsResponse) GetDeptIds() []int64 {
	if x != nil {
		return x.DeptIds
	}
	return nil
}

type CopyColumnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId           int64  `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	OrgId           int64  `protobuf:"varint,2,opt,name=orgId,proto3" json:"orgId,omitempty"`
	TableId         int64  `protobuf:"varint,4,opt,name=tableId,proto3" json:"tableId,omitempty"`
	SourceFieldName string `protobuf:"bytes,5,opt,name=sourceFieldName,proto3" json:"sourceFieldName,omitempty"`
	TargetFieldName string `protobuf:"bytes,6,opt,name=targetFieldName,proto3" json:"targetFieldName,omitempty"`
}

func (x *CopyColumnRequest) Reset() {
	*x = CopyColumnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyColumnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyColumnRequest) ProtoMessage() {}

func (x *CopyColumnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyColumnRequest.ProtoReflect.Descriptor instead.
func (*CopyColumnRequest) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{21}
}

func (x *CopyColumnRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *CopyColumnRequest) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *CopyColumnRequest) GetTableId() int64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *CopyColumnRequest) GetSourceFieldName() string {
	if x != nil {
		return x.SourceFieldName
	}
	return ""
}

func (x *CopyColumnRequest) GetTargetFieldName() string {
	if x != nil {
		return x.TargetFieldName
	}
	return ""
}

type CopyColumnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok              bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	SourceFieldName string `protobuf:"bytes,2,opt,name=sourceFieldName,proto3" json:"sourceFieldName,omitempty"`
	TargetFieldName string `protobuf:"bytes,3,opt,name=targetFieldName,proto3" json:"targetFieldName,omitempty"`
}

func (x *CopyColumnResponse) Reset() {
	*x = CopyColumnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyColumnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyColumnResponse) ProtoMessage() {}

func (x *CopyColumnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyColumnResponse.ProtoReflect.Descriptor instead.
func (*CopyColumnResponse) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{22}
}

func (x *CopyColumnResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CopyColumnResponse) GetSourceFieldName() string {
	if x != nil {
		return x.SourceFieldName
	}
	return ""
}

func (x *CopyColumnResponse) GetTargetFieldName() string {
	if x != nil {
		return x.TargetFieldName
	}
	return ""
}

type GetDataCollaboratorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IssueIds []int64 `protobuf:"varint,1,rep,packed,name=issueIds,proto3" json:"issueIds,omitempty"`
}

func (x *GetDataCollaboratorsRequest) Reset() {
	*x = GetDataCollaboratorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataCollaboratorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataCollaboratorsRequest) ProtoMessage() {}

func (x *GetDataCollaboratorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataCollaboratorsRequest.ProtoReflect.Descriptor instead.
func (*GetDataCollaboratorsRequest) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{23}
}

func (x *GetDataCollaboratorsRequest) GetIssueIds() []int64 {
	if x != nil {
		return x.IssueIds
	}
	return nil
}

type GetDataCollaboratorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataCollaborators []*DataCollaborators `protobuf:"bytes,1,rep,name=dataCollaborators,proto3" json:"dataCollaborators,omitempty"`
}

func (x *GetDataCollaboratorsResponse) Reset() {
	*x = GetDataCollaboratorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataCollaboratorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataCollaboratorsResponse) ProtoMessage() {}

func (x *GetDataCollaboratorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataCollaboratorsResponse.ProtoReflect.Descriptor instead.
func (*GetDataCollaboratorsResponse) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{24}
}

func (x *GetDataCollaboratorsResponse) GetDataCollaborators() []*DataCollaborators {
	if x != nil {
		return x.DataCollaborators
	}
	return nil
}

type DataCollaborators struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IssueId             int64                  `protobuf:"varint,1,opt,name=issueId,proto3" json:"issueId,omitempty"`
	ColumnCollaborators []*ColumnCollaborators `protobuf:"bytes,2,rep,name=columnCollaborators,proto3" json:"columnCollaborators,omitempty"`
}

func (x *DataCollaborators) Reset() {
	*x = DataCollaborators{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataCollaborators) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCollaborators) ProtoMessage() {}

func (x *DataCollaborators) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCollaborators.ProtoReflect.Descriptor instead.
func (*DataCollaborators) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{25}
}

func (x *DataCollaborators) GetIssueId() int64 {
	if x != nil {
		return x.IssueId
	}
	return 0
}

func (x *DataCollaborators) GetColumnCollaborators() []*ColumnCollaborators {
	if x != nil {
		return x.ColumnCollaborators
	}
	return nil
}

type ColumnCollaborators struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ColumnId string  `protobuf:"bytes,1,opt,name=columnId,proto3" json:"columnId,omitempty"`       // 列key
	UserIds  []int64 `protobuf:"varint,2,rep,packed,name=userIds,proto3" json:"userIds,omitempty"` // 用户id列表
	DeptIds  []int64 `protobuf:"varint,3,rep,packed,name=deptIds,proto3" json:"deptIds,omitempty"` // 部门id列表，预留字段，目前用不到
}

func (x *ColumnCollaborators) Reset() {
	*x = ColumnCollaborators{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnCollaborators) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnCollaborators) ProtoMessage() {}

func (x *ColumnCollaborators) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnCollaborators.ProtoReflect.Descriptor instead.
func (*ColumnCollaborators) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{26}
}

func (x *ColumnCollaborators) GetColumnId() string {
	if x != nil {
		return x.ColumnId
	}
	return ""
}

func (x *ColumnCollaborators) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *ColumnCollaborators) GetDeptIds() []int64 {
	if x != nil {
		return x.DeptIds
	}
	return nil
}

type GetAppIdsByCollaboratorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIds []int64 `protobuf:"varint,1,rep,packed,name=userIds,proto3" json:"userIds,omitempty"`
	DeptIds []int64 `protobuf:"varint,2,rep,packed,name=deptIds,proto3" json:"deptIds,omitempty"`
}

func (x *GetAppIdsByCollaboratorReq) Reset() {
	*x = GetAppIdsByCollaboratorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppIdsByCollaboratorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppIdsByCollaboratorReq) ProtoMessage() {}

func (x *GetAppIdsByCollaboratorReq) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppIdsByCollaboratorReq.ProtoReflect.Descriptor instead.
func (*GetAppIdsByCollaboratorReq) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{27}
}

func (x *GetAppIdsByCollaboratorReq) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *GetAppIdsByCollaboratorReq) GetDeptIds() []int64 {
	if x != nil {
		return x.DeptIds
	}
	return nil
}

type GetAppIdsByCollaboratorResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppIds []int64 `protobuf:"varint,1,rep,packed,name=appIds,proto3" json:"appIds,omitempty"`
}

func (x *GetAppIdsByCollaboratorResp) Reset() {
	*x = GetAppIdsByCollaboratorResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_permission_model_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppIdsByCollaboratorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppIdsByCollaboratorResp) ProtoMessage() {}

func (x *GetAppIdsByCollaboratorResp) ProtoReflect() protoreflect.Message {
	mi := &file_permission_model_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppIdsByCollaboratorResp.ProtoReflect.Descriptor instead.
func (*GetAppIdsByCollaboratorResp) Descriptor() ([]byte, []int) {
	return file_permission_model_proto_rawDescGZIP(), []int{28}
}

func (x *GetAppIdsByCollaboratorResp) GetAppIds() []int64 {
	if x != nil {
		return x.AppIds
	}
	return nil
}

var File_permission_model_proto protoreflect.FileDescriptor

var file_permission_model_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x58, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x22, 0x0a,
	0x0c, 0x61, 0x70, 0x70, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x70, 0x70, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49,
	0x64, 0x22, 0x1f, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x76, 0x0a, 0x20, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c,
	0x61, 0x70, 0x70, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x61, 0x70, 0x70, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x23, 0x0a, 0x21, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0xac, 0x01, 0x0a, 0x16, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x70, 0x74, 0x49, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x65, 0x70, 0x74, 0x49, 0x64, 0x22, 0x57,
	0x0a, 0x18, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x05, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62,
	0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x2b, 0x0a, 0x19, 0x43, 0x6f, 0x6c, 0x6c, 0x61,
	0x62, 0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x6f, 0x6b, 0x22, 0xad, 0x01, 0x0a, 0x17, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x6f,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f,
	0x72, 0x67, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x65, 0x70, 0x74, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x65,
	0x70, 0x74, 0x49, 0x64, 0x22, 0x2a, 0x0a, 0x18, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x6f, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x9b, 0x01, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6c, 0x6c,
	0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x6f, 0x72, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x72, 0x67,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x70, 0x74, 0x49, 0x64, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x64, 0x65, 0x70, 0x74, 0x49, 0x64, 0x73, 0x22, 0x3e,
	0x0a, 0x22, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x6f,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x73, 0x22, 0x78,
	0x0a, 0x12, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72,
	0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x25, 0x0a, 0x13, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22,
	0x2d, 0x0a, 0x13, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x73, 0x22, 0x26,
	0x0a, 0x14, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x79, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c,
	0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c, 0x6c, 0x55, 0x73,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x61, 0x6c, 0x6c, 0x55, 0x73, 0x65,
	0x72, 0x22, 0xc1, 0x01, 0x0a, 0x13, 0x41, 0x70, 0x70, 0x50, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x61, 0x73,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x68, 0x61,
	0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x45, 0x64,
	0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x45, 0x64, 0x69,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x61, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x6d, 0x61, 0x6b, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x6d, 0x61, 0x6b, 0x65, 0x22, 0xae, 0x02, 0x0a, 0x0c, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62,
	0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x70, 0x65,
	0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70,
	0x70, 0x50, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x09, 0x70, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x1e, 0x0a, 0x0a,
	0x69, 0x73, 0x53, 0x79, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x69, 0x73, 0x53, 0x79, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x1e, 0x0a, 0x0a,
	0x69, 0x73, 0x53, 0x75, 0x62, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x69, 0x73, 0x53, 0x75, 0x62, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x69, 0x73, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69,
	0x73, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x5d, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c,
	0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x41, 0x0a, 0x0d, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62,
	0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x0d, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x6f, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x8d, 0x01, 0x0a, 0x27, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c,
	0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73,
	0x41, 0x6e, 0x64, 0x44, 0x65, 0x70, 0x74, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x5e, 0x0a, 0x28, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6c,
	0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x41,
	0x6e, 0x64, 0x44, 0x65, 0x70, 0x74, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64,
	0x65, 0x70, 0x74, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x64, 0x65,
	0x70, 0x74, 0x49, 0x64, 0x73, 0x22, 0xad, 0x01, 0x0a, 0x11, 0x43, 0x6f, 0x70, 0x79, 0x43, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x70, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49,
	0x64, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x78, 0x0a, 0x12, 0x43, 0x6f, 0x70, 0x79, 0x43, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x28, 0x0a, 0x0f, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x39, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62,
	0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x73, 0x73, 0x75, 0x65, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x08, 0x69, 0x73, 0x73, 0x75, 0x65, 0x49, 0x64, 0x73, 0x22, 0x6e, 0x0a, 0x1c, 0x47, 0x65,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x11, 0x64, 0x61,
	0x74, 0x61, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62,
	0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x11, 0x64, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6c,
	0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x83, 0x01, 0x0a, 0x11, 0x44,
	0x61, 0x74, 0x61, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x73, 0x75, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x69, 0x73, 0x73, 0x75, 0x65, 0x49, 0x64, 0x12, 0x54, 0x0a, 0x13, 0x63, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x43, 0x6f,
	0x6c, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x13, 0x63, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73,
	0x22, 0x65, 0x0a, 0x13, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62,
	0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x64, 0x65, 0x70, 0x74, 0x49, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07,
	0x64, 0x65, 0x70, 0x74, 0x49, 0x64, 0x73, 0x22, 0x50, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x41, 0x70,
	0x70, 0x49, 0x64, 0x73, 0x42, 0x79, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x64, 0x65, 0x70, 0x74, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x07, 0x64, 0x65, 0x70, 0x74, 0x49, 0x64, 0x73, 0x22, 0x35, 0x0a, 0x1b, 0x47, 0x65, 0x74,
	0x41, 0x70, 0x70, 0x49, 0x64, 0x73, 0x42, 0x79, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x6f, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x49,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x61, 0x70, 0x70, 0x49, 0x64, 0x73,
	0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x65, 0x61, 0x2e, 0x62, 0x6a, 0x78, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2f, 0x4c, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_permission_model_proto_rawDescOnce sync.Once
	file_permission_model_proto_rawDescData = file_permission_model_proto_rawDesc
)

func file_permission_model_proto_rawDescGZIP() []byte {
	file_permission_model_proto_rawDescOnce.Do(func() {
		file_permission_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_permission_model_proto_rawDescData)
	})
	return file_permission_model_proto_rawDescData
}

var file_permission_model_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_permission_model_proto_goTypes = []interface{}{
	(*CreatePermissionGroupRequest)(nil),             // 0: permission.v1.CreatePermissionGroupRequest
	(*CreatePermissionGroupResponse)(nil),            // 1: permission.v1.CreatePermissionGroupResponse
	(*UpdatePermissionGroupInfoRequest)(nil),         // 2: permission.v1.UpdatePermissionGroupInfoRequest
	(*UpdatePermissionGroupInfoResponse)(nil),        // 3: permission.v1.UpdatePermissionGroupInfoResponse
	(*CollaboratorColumnUser)(nil),                   // 4: permission.v1.CollaboratorColumnUser
	(*CollaboratorUsersRequest)(nil),                 // 5: permission.v1.CollaboratorUsersRequest
	(*CollaboratorUsersResponse)(nil),                // 6: permission.v1.CollaboratorUsersResponse
	(*CollaboratorUserRequest)(nil),                  // 7: permission.v1.CollaboratorUserRequest
	(*CollaboratorUserResponse)(nil),                 // 8: permission.v1.CollaboratorUserResponse
	(*GetUserCollaboratorRoleIdsRequest)(nil),        // 9: permission.v1.GetUserCollaboratorRoleIdsRequest
	(*GetUserCollaboratorRoleIdsResponse)(nil),       // 10: permission.v1.GetUserCollaboratorRoleIdsResponse
	(*MemberFieldRequest)(nil),                       // 11: permission.v1.MemberFieldRequest
	(*MemberFieldResponse)(nil),                      // 12: permission.v1.MemberFieldResponse
	(*BatchMigrateRequest)(nil),                      // 13: permission.v1.BatchMigrateRequest
	(*BatchMigrateResponse)(nil),                     // 14: permission.v1.BatchMigrateResponse
	(*GetCollaboratorsRequest)(nil),                  // 15: permission.v1.GetCollaboratorsRequest
	(*AppPerGroupListItem)(nil),                      // 16: permission.v1.AppPerGroupListItem
	(*Collaborator)(nil),                             // 17: permission.v1.Collaborator
	(*GetCollaboratorsResponse)(nil),                 // 18: permission.v1.GetCollaboratorsResponse
	(*GetCollaboratorUserIdsAndDeptIdsRequest)(nil),  // 19: permission.v1.GetCollaboratorUserIdsAndDeptIdsRequest
	(*GetCollaboratorUserIdsAndDeptIdsResponse)(nil), // 20: permission.v1.GetCollaboratorUserIdsAndDeptIdsResponse
	(*CopyColumnRequest)(nil),                        // 21: permission.v1.CopyColumnRequest
	(*CopyColumnResponse)(nil),                       // 22: permission.v1.CopyColumnResponse
	(*GetDataCollaboratorsRequest)(nil),              // 23: permission.v1.GetDataCollaboratorsRequest
	(*GetDataCollaboratorsResponse)(nil),             // 24: permission.v1.GetDataCollaboratorsResponse
	(*DataCollaborators)(nil),                        // 25: permission.v1.DataCollaborators
	(*ColumnCollaborators)(nil),                      // 26: permission.v1.ColumnCollaborators
	(*GetAppIdsByCollaboratorReq)(nil),               // 27: permission.v1.GetAppIdsByCollaboratorReq
	(*GetAppIdsByCollaboratorResp)(nil),              // 28: permission.v1.GetAppIdsByCollaboratorResp
}
var file_permission_model_proto_depIdxs = []int32{
	4,  // 0: permission.v1.CollaboratorUsersRequest.users:type_name -> permission.v1.CollaboratorColumnUser
	16, // 1: permission.v1.Collaborator.perGroups:type_name -> permission.v1.AppPerGroupListItem
	17, // 2: permission.v1.GetCollaboratorsResponse.collaborators:type_name -> permission.v1.Collaborator
	25, // 3: permission.v1.GetDataCollaboratorsResponse.dataCollaborators:type_name -> permission.v1.DataCollaborators
	26, // 4: permission.v1.DataCollaborators.columnCollaborators:type_name -> permission.v1.ColumnCollaborators
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_permission_model_proto_init() }
func file_permission_model_proto_init() {
	if File_permission_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_permission_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePermissionGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePermissionGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePermissionGroupInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePermissionGroupInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollaboratorColumnUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollaboratorUsersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollaboratorUsersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollaboratorUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollaboratorUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserCollaboratorRoleIdsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserCollaboratorRoleIdsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberFieldRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberFieldResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchMigrateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchMigrateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCollaboratorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppPerGroupListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Collaborator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCollaboratorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCollaboratorUserIdsAndDeptIdsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCollaboratorUserIdsAndDeptIdsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyColumnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyColumnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataCollaboratorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataCollaboratorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataCollaborators); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnCollaborators); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppIdsByCollaboratorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_permission_model_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppIdsByCollaboratorResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_permission_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_permission_model_proto_goTypes,
		DependencyIndexes: file_permission_model_proto_depIdxs,
		MessageInfos:      file_permission_model_proto_msgTypes,
	}.Build()
	File_permission_model_proto = out.File
	file_permission_model_proto_rawDesc = nil
	file_permission_model_proto_goTypes = nil
	file_permission_model_proto_depIdxs = nil
}
